/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Mr Scratch' at '11/30/16 5:31 AM' with Gradle 2.14.1
 *
 * @author Mr Scratch, @date 11/30/16 5:31 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
